# Generated by Django 5.0 on 2025-10-22 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('professional_email', models.EmailField(max_length=254, unique=True)),
                ('email_status', models.CharField(blank=True, max_length=100, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('person_linkedin_url', models.URLField(blank=True, null=True)),
                ('person_city', models.CharField(blank=True, max_length=100, null=True)),
                ('person_state', models.CharField(blank=True, max_length=100, null=True)),
                ('person_country', models.CharField(blank=True, max_length=100, null=True)),
                ('person_direct_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(max_length=200)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('employees', models.CharField(blank=True, max_length=50, null=True)),
                ('generic_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('first_address', models.CharField(blank=True, max_length=200, null=True)),
                ('company_city', models.CharField(blank=True, max_length=100, null=True)),
                ('company_state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('company_country', models.CharField(blank=True, max_length=100, null=True)),
                ('company_linkedin_url', models.URLField(blank=True, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('revenue', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Lost', 'Lost')], default='New', max_length=50)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
